name: Model Security CI

on:
  push:
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: sudo apt-get update && sudo apt-get install -y jq

      - name: Export secrets
        run: |
          echo "MODEL_SECURITY_CLIENT_ID=${{ secrets.MODEL_SECURITY_CLIENT_ID }}" >> $GITHUB_ENV
          echo "MODEL_SECURITY_CLIENT_SECRET=${{ secrets.MODEL_SECURITY_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "TSG_ID=${{ secrets.TSG_ID }}" >> $GITHUB_ENV

      - name: Prepare environment
        shell: bash
        run: |
          chmod +x getPYPIurl.sh set_environment.sh
          ./set_environment.sh

      - name: Detect models and run scans
        run: |
          venv/bin/python run_model_scans.py